# Frontend - DEV

# Profil dev local sans contrainte d'auth par defaut
app.security.enabled=${APP_SECURITY_ENABLED:false}

# Aide au diagnostic en dev
logging.level.org.springframework=DEBUG

# Endpoints OIDC locaux par defaut
spring.security.oauth2.client.provider.keycloak.authorization-uri=${KEYCLOAK_AUTH_URL:http://localhost:8080/realms/sma-realm/protocol/openid-connect/auth}
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URL:http://localhost:8080/realms/sma-realm/protocol/openid-connect/token}
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${KEYCLOAK_JWK_SET_URL:http://localhost:8080/realms/sma-realm/protocol/openid-connect/certs}

