# Frontend - LOCAL

server.port=8091
external.service.url=http://localhost:8092
vehicule.json.path=classpath:vehicules.json

spring.thymeleaf.cache=false
logging.level.org.springframework=DEBUG
logging.file.path=/home/cdn/IdeaProjects/sma-eventsourcing-17/frontend/logs
