services:
  thymeleaf-frontend:
    build:
      context: ./thymeleaf-frontend
      dockerfile: Dockerfile
    container_name: thymeleaf-frontend
    ports:
      - '8091:8091'
    expose:
      - '8091'
    depends_on:
      sma-monolithe:
        condition: service_healthy
    networks:
        - monolithe-network

  sma-monolithe:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: sma-monolithe
    ports:
      - '8092:8092'
    expose:
      - '8092'
    depends_on:
      postgres-monolithe:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres-monolithe
      POSTGRES_PORT: 5432
      POSTGRES_DB: monolithe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      start_period: 30s
      test: ["CMD", "curl", "-f", "http://sma-monolithe:8092/actuator/health"]
      interval: 20s
      retries: 5
    networks:
        - monolithe-network

  postgres-monolithe:
    image: postgres
#    build:
#      context: .
#      dockerfile: Dockerfile.bdd
    container_name: postgres-monolithe
    volumes:
      - pg_monolithe:/var/lib/postgresql/data
      - ./docker/initdb_postgres.sh:/docker-entrypoint-initdb.d/initdb_postgres.sh
    environment:
      POSTGRES_DB: monolithe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#      POSTGRES_DB_USER: kiki
#      POSTGRES_DB_PASSWORD: kikipassword
    ports:
      - '5432:5432'
    command: -p 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
    networks:
        - monolithe-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "6002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data_monolithe:/var/lib/pgadmin
    networks:
        - monolithe-network

volumes:
  pg_monolithe:
  pgadmin_data_monolithe:

networks:
  monolithe-network:
    driver: bridge
