<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.cdrochon</groupId>
    <artifactId>sma-eventsourcing-17-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>sma-eventsourcing-17-parent</name>
    <description>Parent Maven multi-modules pour backend et frontend</description>
    <properties>
        <!-- Définit l'encodage source du projet : utile pour Maven, Sonar et éditeurs -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- Propriété Sonar pour forcer l'encodage lors de l'analyse -->
        <sonar.sourceEncoding>UTF-8</sonar.sourceEncoding>
        <sonar.exclusions>**/target/**,**/logs/**,**/*.class,**/*.log,**/*.gz,**/*.zip,**/static/img/**</sonar.exclusions>
        <!-- Java source/target par défaut (peut être surchargé dans modules) -->
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <modules>
        <module>backend</module>
        <module>frontend</module>
    </modules>
</project>
