# Backend - LOCAL

server.port=8092

# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/monolithe
spring.datasource.username=postgres
spring.datasource.password=password

# Audit RGPD datasource local
audit.datasource.url=jdbc:postgresql://localhost:5432/audit
audit.datasource.username=postgres
audit.datasource.password=password

# Axon local
axon.axonserver.servers=localhost:8124

# Keycloak (desactive en local pour dev rapide)
app.security.enabled=false
app.security.require-authenticated-all=false
app.security.audit-endpoints-authenticated=false
app.security.audit-required-roles=ADMIN,AUDITOR
app.security.audit-writer-roles=ADMIN
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/sma-realm

# Logs dev
spring.jpa.show-sql=true
logging.level.org.springframework=DEBUG
logging.file.path=/home/cdn/IdeaProjects/sma-eventsourcing-17/backend/logs
