# Backend - LOCAL

server.port=8092

# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/monolithe
spring.datasource.username=postgres
spring.datasource.password=password

# Audit RGPD datasource local
audit.datasource.url=jdbc:postgresql://localhost:5432/audit
audit.datasource.username=postgres
audit.datasource.password=password

# Axon local
axon.axonserver.servers=localhost:8124

# Logs dev
spring.jpa.show-sql=true
logging.level.org.springframework=DEBUG
logging.file.path=/home/cdn/IdeaProjects/sma-eventsourcing-17/backend/logs
