# Backend - PROD (Docker)

server.port=8092

# PostgreSQL via Docker
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres-monolithe}:${POSTGRES_PORT:5432}/${POSTGRES_DB:monolithe}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}

# Audit RGPD datasource via Docker
audit.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres-monolithe}:${POSTGRES_PORT:5432}/audit
audit.datasource.username=${POSTGRES_USER:postgres}
audit.datasource.password=${POSTGRES_PASSWORD:password}

# Axon via Docker
axon.axonserver.servers=${AXON_AXONSERVER_SERVERS:axon-server:8124}

# Keycloak (prod)
app.security.enabled=${APP_SECURITY_ENABLED:true}
app.security.require-authenticated-all=${APP_SECURITY_REQUIRE_AUTHENTICATED_ALL:false}
app.security.audit-endpoints-authenticated=${APP_SECURITY_AUDIT_ENDPOINTS_AUTHENTICATED:true}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL:http://keycloak:8080/realms/sma-realm}

# Logs plus sobres
spring.jpa.show-sql=false
logging.level.org.springframework=INFO
logging.file.path=${LOGGING_FILE_PATH:/app/logs/backend}
