package fr.cdrochon.thymeleaffrontend.dtos.document;

public enum DocumentStatusDTO {
    
    CREATED,
    SENT,
    PAID,
    CANCELLED,
    REFUSED,
    ACCEPTED,
    IN_PROGRESS,
    COMPLETED,
    ARCHIVED,
    DELETED,
    DRAFT,
    VALIDATED,
    TO_BE_VALIDATED,
    TO_BE_PAID,
    TO_BE_SENT,
    TO_BE_ACCEPTED,
    TO_BE_REFUSED,
    TO_BE_COMPLETED,
    TO_BE_ARCHIVED,
    TO_BE_DELETED,
    TO_BE_CANCELLED,
    TO_BE_PAID_AND_SENT,
    TO_BE_PAID_AND_SENT_AND_ACCEPTED,
    TO_BE_PAID_AND_SENT_AND_ACCEPTED_AND_COMPLETED,
    TO_BE_PAID_AND_SENT_AND_ACCEPTED_AND_COMPLETED_AND_ARCHIVED,
    TO_BE_PAID_AND_SENT_AND_ACCEPTED_AND_COMPLETED_AND_ARCHIVED_AND_DELETED,
    TO_BE_PAID_AND_SENT_AND_ACCEPTED_AND_COMPLETED_AND_ARCHIVED_AND_DELETED_AND_REFUSED
}
