# Backend - PROD

# PostgreSQL via Docker / serveur
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres-monolithe}:${POSTGRES_PORT:5432}/${POSTGRES_DB:monolithe}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Audit RGPD
audit.datasource.url=jdbc:postgresql://${AUDIT_POSTGRES_HOST:${POSTGRES_HOST:postgres-monolithe}}:${AUDIT_POSTGRES_PORT:${POSTGRES_PORT:5432}}/${AUDIT_POSTGRES_DB:audit}
audit.datasource.username=${AUDIT_POSTGRES_USER:${POSTGRES_USER}}
audit.datasource.password=${AUDIT_POSTGRES_PASSWORD:${POSTGRES_PASSWORD}}

# Axon via Docker
axon.axonserver.servers=${AXON_AXONSERVER_SERVERS:axon-server:8124}

# Keycloak prod
app.security.enabled=${APP_SECURITY_ENABLED:true}
app.security.audit-endpoints-authenticated=${APP_SECURITY_AUDIT_ENDPOINTS_AUTHENTICATED:true}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL:http://keycloak:8080/realms/sma-realm}

# Logs prod
spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.file.path=${LOGGING_FILE_PATH:/app/logs/backend}