# Backend - DEV

# Profil dev local (hors conteneur) avec Keycloak optionnel
app.security.enabled=${APP_SECURITY_ENABLED:false}
app.security.require-authenticated-all=${APP_SECURITY_REQUIRE_AUTHENTICATED_ALL:false}
app.security.audit-endpoints-authenticated=${APP_SECURITY_AUDIT_ENDPOINTS_AUTHENTICATED:true}
app.security.swagger-public=${APP_SECURITY_SWAGGER_PUBLIC:true}

# Swagger/OpenAPI actif en dev
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}

# Axon et Keycloak cibles locales par defaut
axon.axonserver.servers=${AXON_AXONSERVER_SERVERS:localhost:8124}
axon.axonserver.context=${AXON_AXONSERVER_CONTEXT:default}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL:http://localhost:8080/realms/sma-realm}
