package fr.cdrochon.thymeleaffrontend.dtos.client;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum PaysDTO {
//    ALBANIE, FRANCE, TOGO;
    
            AFGHANISTAN,
            ALBANIE,
            ALGERIE,
            ANDORRE,
            ANGOLA,
            ANTIGUA_ET_BARBUDA,
            ARABIE_SAOUDITE,
            ARGENTINE,
            ARMENIE,
            AUSTRALIE,
            AUTRICHE,
            AZERBAIDJAN,
            BAHAMAS,
            BAHREIN,
            BANGLADESH,
            BARBADE,
            BELGIQUE,
            BELIZE,
            BENIN,
            BHOUTAN,
            BIELORUSSIE,
            BIRMANIE,
            BOLIVIE,
            BOSNIE_HERZEGOVINE,
            BOTSWANA,
            BRESIL,
            BRUNEI,
            BULGARIE,
            BURKINA_FASO,
            BURUNDI,
            CABO_VERDE,
            CAMBODGE,
            CAMEROUN,
            CANADA,
            CENTRAFRIQUE,
            CHILI,
            CHINE,
            CHYPRE,
            COLOMBIE,
            COMORES,
            CONGO,
            COREE_DU_NORD,
            COREE_DU_SUD,
            COSTA_RICA,
            COTE_DIVOIRE,
            CROATIE,
            CUBA,
            DANEMARK,
            DJIBOUTI,
            DOMINIQUE,
            EGYPTE,
            EMIRATS_ARABES_UNIS,
            EQUATEUR,
            ERYTHREE,
            ESPAGNE,
            ESTONIE,
            ESWATINI,
            ETATS_UNIS,
            ETHIOPIE,
            FIDJI,
            FINLANDE,
            FRANCE,
            GABON,
            GAMBIE,
            GEORGIE,
            GHANA,
            GRECE,
            GRENADE,
            GUATEMALA,
            GUINEE,
            GUINEE_BISSAU,
            GUYANA,
            HAITI,
            HONDURAS,
            HONGRIE,
            INDE,
            INDONESIE,
            IRAN,
            IRAK,
            IRLANDE,
            ISLANDE,
            ISRAEL,
            ITALIE,
            JAMAIQUE,
            JAPON,
            JORDANIE,
            KAZAKHSTAN,
            KENYA,
            KIRGHIZISTAN,
            KIRIBATI,
            KOWEIT,
            LAOS,
            LESOTHO,
            LETTONIE,
            LIBAN,
            LIBERIA,
            LIBYE,
            LIECHTENSTEIN,
            LITUANIE,
            LUXEMBOURG,
            MACEDOINE,
            MADAGASCAR,
            MALAWI,
            MALAISIE,
            MALDIVES,
            MALI,
            MALTE,
            MAROC,
            MARSHALL,
            MAURICE,
            MAURITANIE,
            MEXIQUE,
            MICRONESIE,
            MOLDAVIE,
            MONACO,
            MONGOLIE,
            MONTENEGRO,
            MOZAMBIQUE,
            NAMIBIE,
            NAURU,
            NEPAL,
            NICARAGUA,
            NIGER,
            NIGERIA,
            NORVEGE,
            NOUVELLE_ZELANDE,
            OMAN,
            OUGANDA,
            OUZBEKISTAN,
            PAKISTAN,
            PALAOS,
            PALESTINE,
            PANAMA,
            PAPOUASIE_NOUVELLE_GUINEE,
            PARAGUAY,
            PAYS_BAS,
            PEROU,
            PHILIPPINES,
            POLOGNE,
            PORTUGAL,
            QATAR,
            REPUBLIQUE_DOMINICAINE,
            REPUBLIQUE_TCHEQUE,
            ROUMANIE,
            ROYAUME_UNI,
            RUSSIE,
            RWANDA,
            SAINT_KITTS_ET_NEVIS,
            SAINT_MARIN,
            SAINT_VINCENT_ET_LES_GRENADINES,
            SAINTE_LUCIE,
            SALVADOR,
            SAMOA,
            SAO_TOME_ET_PRINCIPE,
            SENEGAL,
            SERBIE,
            SEYCHELLES,
            SIERRA_LEONE,
            SINGAPOUR,
            SLOVAQUIE,
            SLOVENIE,
            SOMALIE,
            SOUDAN,
            SOUDAN_DU_SUD,
            SRI_LANKA,
            SUEDE,
            SUISSE,
            SURINAME,
            SYRIE,
            TADJIKISTAN,
            TANZANIE,
            TCHAD,
            THAILANDE,
            TIMOR_ORIENTAL,
            TOGO,
            TONGA,
            TRINITE_ET_TOBAGO,
            TUNISIE,
            TURKMENISTAN,
            TURQUIE,
            TUVALU,
            UKRAINE,
            URUGUAY,
            VANUATU,
            VATICAN,
            VENEZUELA,
            VIETNAM,
            YEMEN,
            ZAMBIE,
            ZIMBABWE;
    
    
    //    AFGHANISTAN("Afghanistan"),
    //    ALBANIA("Albania"),
    //    ALGERIA("Algeria"),
    //    ANDORRA("Andorra"),
    //    ANGOLA("Angola"),
    //    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    //    ARGENTINA("Argentina"),
    //    ARMENIA("Armenia"),
    //    AUSTRALIA("Australia"),
    //    AUSTRIA("Austria"),
    //    AZERBAIJAN("Azerbaijan"),
    //    BAHAMAS("Bahamas"),
    //    BAHRAIN("Bahrain"),
    //    BANGLADESH("Bangladesh"),
    //    BARBADOS("Barbados"),
    //    BELARUS("Belarus"),
    //    BELGIUM("Belgium"),
    //    BELIZE("Belize"),
    //    BENIN("Benin"),
    //    BHUTAN("Bhutan"),
    //    BOLIVIA("Bolivia"),
    //    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    //    BOTSWANA("Botswana"),
    //    BRAZIL("Brazil"),
    //    BRUNEI("Brunei"),
    //    BULGARIA("Bulgaria"),
    //    BURKINA_FASO("Burkina Faso"),
    //    BURUNDI("Burundi"),
    //    CABO_VERDE("Cabo Verde"),
    //    CAMBODIA("Cambodia"),
    //    CAMEROON("Cameroon"),
    //    CANADA("Canada"),
    //    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    //    CHAD("Chad"),
    //    CHILE("Chile"),
    //    CHINA("China"),
    //    COLOMBIA("Colombia"),
    //    COMOROS("Comoros"),
    //    CONGO_DEMOCRATIC_REPUBLIC("Congo, Democratic Republic"),
    //    CONGO_REPUBLIC("Congo, Republic"),
    //    COSTA_RICA("Costa Rica"),
    //    COTE_DIVOIRE("Côte d'Ivoire"),
    //    CROATIA("Croatia"),
    //    CUBA("Cuba"),
    //    CYPRUS("Cyprus"),
    //    CZECH_REPUBLIC("Czech Republic"),
    //    DENMARK("Denmark"),
    //    DJIBOUTI("Djibouti"),
    //    DOMINICA("Dominica"),
    //    DOMINICAN_REPUBLIC("Dominican Republic"),
    //    EAST_TIMOR("East Timor"),
    //    ECUADOR("Ecuador"),
    //    EGYPT("Egypt"),
    //    EL_SALVADOR("El Salvador"),
    //    EQUATORIAL_GUINEA("Equatorial Guinea"),
    //    ERITREA("Eritrea"),
    //    ESTONIA("Estonia"),
    //    ESWATINI("Eswatini"),
    //    ETHIOPIA("Ethiopia"),
    //    FIJI("Fiji"),
    //    FINLAND("Finland"),
    //    FRANCE("France"),
    //    GABON("Gabon"),
    //    GAMBIA("Gambia"),
    //    GEORGIA("Georgia"),
    //    GERMANY("Germany"),
    //    GHANA("Ghana"),
    //    GREECE("Greece"),
    //    GRENADA("Grenada"),
    //    GUATEMALA("Guatemala"),
    //    GUINEA("Guinea"),
    //    GUINEA_BISSAU("Guinea-Bissau"),
    //    GUYANA("Guyana"),
    //    HAITI("Haiti"),
    //    HONDURAS("Honduras"),
    //    HUNGARY("Hungary"),
    //    ICELAND("Iceland"),
    //    INDIA("India"),
    //    INDONESIA("Indonesia"),
    //    IRAN("Iran"),
    //    IRAQ("Iraq"),
    //    IRELAND("Ireland"),
    //    ISRAEL("Israel"),
    //    ITALY("Italy"),
    //    JAMAICA("Jamaica"),
    //    JAPAN("Japan"),
    //    JORDAN("Jordan"),
    //    KAZAKHSTAN("Kazakhstan"),
    //    KENYA("Kenya"),
    //    KIRIBATI("Kiribati"),
    //    KOREA_NORTH("Korea, North"),
    //    KOREA_SOUTH("Korea, South"),
    //    KOSOVO("Kosovo"),
    //    KUWAIT("Kuwait"),
    //    KYRGYZSTAN("Kyrgyzstan"),
    //    LAOS("Laos"),
    //    LATVIA("Latvia"),
    //    LEBANON("Lebanon"),
    //    LESOTHO("Lesotho"),
    //    LIBERIA("Liberia"),
    //    LIBYA("Libya"),
    //    LIECHTENSTEIN("Liechtenstein"),
    //    LITHUANIA("Lithuania"),
    //    LUXEMBOURG("Luxembourg"),
    //    MADAGASCAR("Madagascar"),
    //    MALAWI("Malawi"),
    //    MALAYSIA("Malaysia"),
    //    MALDIVES("Maldives"),
    //    MALI("Mali"),
    //    MALTA("Malta"),
    //    MARSHALL_ISLANDS("Marshall Islands"),
    //    MAURITANIA("Mauritania"),
    //    MAURITIUS("Mauritius"),
    //    MEXICO("Mexico"),
    //    MICRONESIA("Micronesia"),
    //    MOLDOVA("Moldova"),
    //    MONACO("Monaco"),
    //    MONGOLIA("Mongolia"),
    //    MONTENEGRO("Montenegro"),
    //    MOROCCO("Morocco"),
    //    MOZAMBIQUE("Mozambique"),
    //    MYANMAR("Myanmar"),
    //    NAMIBIA("Namibia"),
    //    NAURU("Nauru"),
    //    NEPAL("Nepal"),
    //    NETHERLANDS("Netherlands"),
    //    NEW_ZEALAND("New Zealand"),
    //    NICARAGUA("Nicaragua"),
    //    NIGER("Niger"),
    //    NIGERIA("Nigeria"),
    //    NORTH_MACEDONIA("North Macedonia"),
    //    NORWAY("Norway"),
    //    OMAN("Oman"),
    //    PAKISTAN("Pakistan"),
    //    PALAU("Palau"),
    //    PALESTINE("Palestine"),
    //    PANAMA("Panama"),
    //    PAPUA_NEW_GUINEA("Papua New Guinea"),
    //    PARAGUAY("Paraguay"),
    //    PERU("Peru"),
    //    PHILIPPINES("Philippines"),
    //    POLAND("Poland"),
    //    PORTUGAL("Portugal"),
    //    QATAR("Qatar"),
    //    ROMANIA("Romania"),
    //    RUSSIA("Russia"),
    //    RWANDA("Rwanda"),
    //    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    //    SAINT_LUCIA("Saint Lucia"),
    //    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    //    SAMOA("Samoa"),
    //    SAN_MARINO("San Marino"),
    //    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    //    SAUDI_ARABIA("Saudi Arabia"),
    //    SENEGAL("Senegal"),
    //    SERBIA("Serbia"),
    //    SEYCHELLES("Seychelles"),
    //    SIERRA_LEONE("Sierra Leone"),
    //    SINGAPORE("Singapore"),
    //    SLOVAKIA("Slovakia"),
    //    SLOVENIA("Slovenia"),
    //    SOLOMON_ISLANDS("Solomon Islands"),
    //    SOMALIA("Somalia"),
    //    SOUTH_AFRICA("South Africa"),
    //    SOUTH_SUDAN("South Sudan"),
    //    SPAIN("Spain"),
    //    SRI_LANKA("Sri Lanka"),
    //    SUDAN("Sudan"),
    //    SURINAME("Suriname"),
    //    SWEDEN("Sweden"),
    //    SWITZERLAND("Switzerland"),
    //    SYRIA("Syria"),
    //    TAIWAN("Taiwan"),
    //    TAJIKISTAN("Tajikistan"),
    //    TANZANIA("Tanzania"),
    //    THAILAND("Thailand"),
    //    TOGO("Togo"),
    //    TONGA("Tonga"),
    //    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    //    TUNISIA("Tunisia"),
    //    TURKEY("Turkey"),
    //    TURKMENISTAN("Turkmenistan"),
    //    TUVALU("Tuvalu"),
    //    UGANDA("Uganda"),
    //    UKRAINE("Ukraine"),
    //    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    //    UNITED_KINGDOM("United Kingdom"),
    //    UNITED_STATES("United States"),
    //    URUGUAY("Uruguay"),
    //    UZBEKISTAN("Uzbekistan"),
    //    VANUATU("Vanuatu"),
    //    VATICAN_CITY("Vatican City"),
    //    VENEZUELA("Venezuela"),
    //    VIETNAM("Vietnam"),
    //    YEMEN("Yemen"),
    //    ZAMBIA("Zambia"),
    //    ZIMBABWE("Zimbabwe");
    //
    //
    //    private final String displayName;
    //
    //    PaysDTO(String displayName) {
    //        this.displayName = displayName;
    //    }
    
    //    private final String displayName;
    //
    //    PaysDTO(String displayName) {
    //        this.displayName = displayName;
    //    }
    //
    //    public static PaysDTO getDefault() {
    //        return PaysDTO.FRANCE;
    //    }
    
    //    @JsonValue
    //    public String getDisplayName() {
    //        return displayName;
    //
    //    }
    
    @JsonCreator
    public static PaysDTO forValue(String value) {
        for(PaysDTO status : values()) {
            if(status.name().equalsIgnoreCase(value)) {
                return status;
            }
        }
        return FRANCE; // Default value for unknown enum values
    }
    
    @JsonValue
    public String getLabel() {
        return this.name();
    }
    
    // Méthode pour obtenir la valeur par défaut
    public static PaysDTO valeurPaysParDefaut() {
        return FRANCE; // Retourne la valeur par défaut
    }
    
}
