apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: thymeleaf-frontend
  name: thymeleaf-frontend
  namespace: smb
spec:
  type: LoadBalancer
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    io.kompose.service: thymeleaf-frontend
